print("========="*8)
print("\t\tREGISTRASI UANG KAGET AHMADRAFI")
print("========="*8)
Nama=str(input("Masukkan Nama Anda : "))
Tingi_Badan=float(input("Masukkan Tinggi Badan Anda (dalam cm) : "))
Umur=int(input("Masukkan Umur Anda : "))
No_Telp=int(input("Masukkan Nomor Telepon Anda : "))
No_ATM=int(input("Masukkan Nomor ATM Anda : "))
Pw_ATM=int(input("Masukkan Password ATM Anda : "))
Alamat=str(input("Masukkan Alamat Tempat Tinggal Anda : "))
Is_umur= Umur >= 17
print("========="*8)
print("=========DATA ANDA SUDAH TEREGISTRASI=========")
print(f"Nama Anda\t\t:\t {Nama}")
print(f"Tinggi Badan Anda\t:\t {Tingi_Badan} cm")
print(f"Umur Anda\t\t:\t {Umur} Tahun, dan sudah cukup umur: {Is_umur}")
print(f"Nomor Telepon Anda\t:\t {No_Telp}")
print(f"Nomor ATM Anda\t\t:\t {No_ATM}")
print(f"Password ATM Anda\t:\t {Pw_ATM}")
print(f"Alamat Tempat Tinggal Anda:\t {Alamat}")
print("==========TERIMA KASIH SUDAH MELAKUKAN REGISTRASI==========") 
print("====ANDA MENDAPATKAN UANG KAGET SEBESAR 1 MILYAR RUPIAH====")
print("===========================================================")   
